const LOAD_DATA = 'LOAD_DATA';
const ADD_TODOS = 'ADD_TODOS';
const CHANGE_TYPE = 'CHANGE_TYPE';
const CHANGE_TYPE_ALL = 'CHANGE_TYPE_ALL';
const DELETE_TASK = 'DELETE_TASK';
const EDIT_TASK = 'EDIT_TASK';
const CLEAR_TASK_COMPLETED = 'CLEAR_TASK_COMPLETED';
const CALLING_SERVER = 'CALLING_SERVER';
const CALLED_SERVER = 'CALLED_SERVER';

export {
	LOAD_DATA,
	ADD_TODOS,
	CHANGE_TYPE,
	CHANGE_TYPE_ALL,
	DELETE_TASK,
	EDIT_TASK,
	CLEAR_TASK_COMPLETED,
	CALLING_SERVER,
	CALLED_SERVER,
};
